### ISSUE TITLE
deployment to heroku not working

### ISSUE THREAD

**Issue by rohan-paul** [rohan-paul/chainable-dropdown-list#3]
While after pushing to Heroku (git push heroku master), Terminal is showing to the below URL as the deployed URL - But thats not working - Spent 4 / 5 hours to fix it around Proxy in React, correct way to declare Car variable in models, and MongoDB configuration (comparing with my othre app DevBook) - but ultimately failed.

[https://intense-wildwood-81995.herokuapp.com/](https://intense-wildwood-81995.herokuapp.com/)

Getting the following error after running ``heroku logs --tail``

```
 at startup (bootstrap_node.js:191:16)
2018-09-07T20:39:18.587268+00:00 app[web.1]: at bootstrap_node.js:612:3
2018-09-07T20:39:18.598638+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-09-07T20:39:18.599139+00:00 app[web.1]: npm ERR! errno 1
2018-09-07T20:39:18.600175+00:00 app[web.1]: npm ERR! ReactDropDown@1.0.0 start: `node server.js`
2018-09-07T20:39:18.600284+00:00 app[web.1]: npm ERR! Exit status 1
2018-09-07T20:39:18.600466+00:00 app[web.1]: npm ERR!
2018-09-07T20:39:18.600717+00:00 app[web.1]: npm ERR! Failed at the ReactDropDown@1.0.0 start script.
2018-09-07T20:39:18.600843+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-09-07T20:39:18.649956+00:00 app[web.1]: 
2018-09-07T20:39:18.650199+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-09-07T20:39:18.650428+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-09-07T20_39_18_602Z-debug.log
2018-09-07T20:39:18.705372+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-07T20:39:18.707066+00:00 heroku[web.1]: State changed from crashed to starting
2018-09-07T20:39:18.691269+00:00 heroku[web.1]: Process exited with status 1
2018-09-07T20:39:31.015123+00:00 heroku[web.1]: Starting process with command `npm start`
2018-09-07T20:39:33.510956+00:00 app[web.1]: 
2018-09-07T20:39:33.510981+00:00 app[web.1]: > ReactDropDown@1.0.0 start /app
2018-09-07T20:39:33.510983+00:00 app[web.1]: > node server.js
2018-09-07T20:39:33.510984+00:00 app[web.1]: 
2018-09-07T20:39:35.394182+00:00 app[web.1]: 
2018-09-07T20:39:35.394229+00:00 app[web.1]: /app/node_modules/mongoose/lib/connection.js:424
2018-09-07T20:39:35.394231+00:00 app[web.1]: throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
2018-09-07T20:39:35.394233+00:00 app[web.1]: ^
2018-09-07T20:39:35.394706+00:00 app[web.1]: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
2018-09-07T20:39:35.394710+00:00 app[web.1]: at new MongooseError (/app/node_modules/mongoose/lib/error/mongooseError.js:13:11)
2018-09-07T20:39:35.394712+00:00 app[web.1]: at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:424:11)
2018-09-07T20:39:35.394713+00:00 app[web.1]: at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:232:15)
2018-09-07T20:39:35.394715+00:00 app[web.1]: at Object.<anonymous> (/app/server.js:27:4)
2018-09-07T20:39:35.394717+00:00 app[web.1]: at Module._compile (module.js:652:30)
2018-09-07T20:39:35.394720+00:00 app[web.1]: at Module.load (module.js:565:32)
2018-09-07T20:39:35.394719+00:00 app[web.1]: at Object.Module._extensions..js (module.js:663:10)
2018-09-07T20:39:35.394722+00:00 app[web.1]: at tryModuleLoad (module.js:505:12)
2018-09-07T20:39:35.394724+00:00 app[web.1]: at Function.Module._load (module.js:497:3)
2018-09-07T20:39:35.394725+00:00 app[web.1]: at Function.Module.runMain (module.js:693:10)
2018-09-07T20:39:35.394727+00:00 app[web.1]: at startup (bootstrap_node.js:191:16)
2018-09-07T20:39:35.394729+00:00 app[web.1]: at bootstrap_node.js:612:3
2018-09-07T20:39:35.409783+00:00 app[web.1]: npm ERR! errno 1
2018-09-07T20:39:35.409079+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-09-07T20:39:35.412118+00:00 app[web.1]: npm ERR! ReactDropDown@1.0.0 start: `node server.js`
2018-09-07T20:39:35.412384+00:00 app[web.1]: npm ERR! Exit status 1
2018-09-07T20:39:35.412781+00:00 app[web.1]: npm ERR!
2018-09-07T20:39:35.413072+00:00 app[web.1]: npm ERR! Failed at the ReactDropDown@1.0.0 start script.
2018-09-07T20:39:35.413319+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-09-07T20:39:35.422350+00:00 app[web.1]: 
2018-09-07T20:39:35.422671+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-09-07T20:39:35.422895+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-09-07T20_39_35_415Z-debug.log
2018-09-07T20:39:35.500167+00:00 heroku[web.1]: Process exited with status 1
2018-09-07T20:39:35.517571+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-07T20:40:05.410409+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-wildwood-81995.herokuapp.com request_id=867718eb-77b7-4552-9a50-8e44d30c7f53 fwd="183.83.72.180" dyno= connect= service= status=503 bytes= protocol=https
2018-09-07T20:40:06.711996+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-wildwood-81995.herokuapp.com request_id=181714dc-163d-4a21-9900-afce776e4831 fwd="183.83.72.180" dyno= connect= service= status=503 bytes= protocol=https
2018-09-07T20:40:21.073289+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=intense-wildwood-81995.herokuapp.com request_id=06e9df86-af06-411d-95e3-884669bcc593 fwd="183.83.72.180" dyno= connect= service= status=503 bytes= protocol=https
2018-09-07T20:40:22.368312+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=intense-wildwood-81995.herokuapp.com request_id=443853e3-f928-428d-807b-95c0b0723ab1 fwd="183.83.72.180
```

**Comment by malikgenius** [comment]
did you fix it, i just got this weird error on my MERN app ... if anybody fixed it please share
